### ISSUE TITLE
Header length is encoded as little-endian, whereas network byte order is big-endian

### ISSUE THREAD

**Issue by harmanpa** [mtiller/recon#13]
The methods in util.py use little-endian encoding, network ordering / msgpack / Java / Javascript are all big-endian, so this may be more appropriate?

**Comment by xogeny** [comment]
Agreed.  I just wanted to avoid native.  But in looking at the documentation for the [struct module](http://docs.python.org/2/library/struct.html), I clearly should have paid attention to network order.

I'll fix this right away.  Fortunately, it is all contained in one place.
