### ISSUE TITLE
File type header version number can't go beyond 9

### ISSUE THREAD

**Issue by harmanpa** [mtiller/recon#14]
"recon:meld:v10" isn't possible, because we read a fixed-length string. If it gets to version 10...

**Comment by xogeny** [comment]
Ha!  Decimal Thinking!  You forget about "recon:meld:va" :-)

But you have a point.  We could pad this.  Are you proposing "recon:meld:v01" ?

**Comment by xogeny** [comment]
If this isn't satisfactory, feel free to reopen.
