### ISSUE TITLE
Should DyMat (and SciPy) be added to install_requires?

### ISSUE THREAD

**Issue by tbeu** [mtiller/recon#41]
There is DyMat required which itself requires SciPy.
- Unfortunately there is no DyMat-package on PyPi that can be downloaded by the setuptools.
- Unfortunately setup.py of DyMat does not list SciPy as requirement.

**Comment by xogeny** [comment]
This is technically only required for the translation feature.  What I propose (as an alternative) is to catch errors when these imports fail and provide a diagnostic explaining the package format.

**Comment by xogeny** [comment]
One thought...perhaps all the dsres related stuff could be broken out into a separate package (with a greater number of dependencies).  This would keep the core recon library small with a minimum of dependencies and then install all the necessary additional bits if someone specifically wanted the dsres translation capabilities?  Alternatively, I have a pure Python generated based dsres reader around somewhere that I could integrate...

**Comment by tbeu** [comment]
Agreed. All dsres related stuff should go to an extra package.
